spring:
  application:
    name: "payment-service"
  profiles:
    active: ${PAYMENT_PROFILE:dev}

  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      pool-name: payment-hikari-pool
      maximum-pool-size: 10       # 기본 개발용
      minimum-idle: 5
      idle-timeout: 600000        # 10분
      max-lifetime: 1800000       # 30분
      connection-timeout: 30000   # 30초

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

springdoc:
  use-fqn: true

server:
  port: ${SERVER_PORT}

service:
  product:
    url: ${PRODUCT_SERVICE_URL}
  order:
    url: ${ORDER_SERVICE_URL}
  payment:
    url: ${PAYMENT_SERVICE_URL}

payment:
  toss:
    client_api_key: ${TOSS_CLIENT_API_KEY}
    secret_api_key: ${TOSS_SECRET_API_KEY}
    success_url: ${TOSS_SUCCESS_URL}
    fail_url: ${TOSS_FAIL_URL}